In [1]:
#Using Numpy handson
# The first step of using numpy is to tell python to import it
import numpy as np

In [8]:
prec_on_time = [0.62, 0.78, 0.20, 0.32, 0.85]
[i for i,x in enumerate(prec_on_time) if x >0.5]

[0, 1, 4]

In [9]:
# defining a list of different car companies or string elements
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']

# defining a list of number of cylinders in car or numerical elements
arr_num = [5, 4, 6, 7, 3]

In [10]:
arr_num

[5, 4, 6, 7, 3]

In [16]:

# connverting the list arr_str to a NumPy array
np_arr_str = np.array(arr_str)


# connverting the list arr_num to a NumPy array
np_arr_num = np.array(arr_num)

# checking the output
print('Numpy Array (arr_str): ',np_arr_str)
print('Numpy Array (arr_num): ',np_arr_num)

Numpy Array (arr_str):  ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
Numpy Array (arr_num):  [5 4 6 7 3]


In [17]:
# printing the data type of lists
print('Data type of arr_str: ',type(arr_str))
print('Data type of arr_num: ',type(arr_num))

# printing the data type after conversion of lists to array
print('Data type of np_arr_str: ',type(np_arr_str))
print('Data type of np_arr_num: ',type(np_arr_num))

Data type of arr_str:  <class 'list'>
Data type of arr_num:  <class 'list'>
Data type of np_arr_str:  <class 'numpy.ndarray'>
Data type of np_arr_num:  <class 'numpy.ndarray'>


In [20]:
# let's say we have information of different number of cylinders in a car and we want to display them in a matrix format
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)
print('Data type of matrix: ',type(matrix))

[[1 2 1]
 [4 5 9]
 [1 8 9]]
Data type of matrix:  <class 'numpy.ndarray'>


In [23]:
arr2  = np.arange(start = 0, stop = 10) # 10 will be excluded from the output
print('arr2\n',arr2)

arr3  = np.arange(0,10) 
print('arr3\n',arr3)

arr2
 [0 1 2 3 4 5 6 7 8 9]
arr3
 [0 1 2 3 4 5 6 7 8 9]


In [42]:
# by default 50 evenly spaced values will be generated between 0 and 5
matrix2 = np.linspace(0, 5)
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [46]:
matrix4 = np.zeros([3,5])
print('matrix4:\n', matrix4)

matrix5 = np.ones([3,5])
print('\nmatrix5:\n', matrix5)

matrix6 = np.eye(5)
print('\nmatrix eye:\n', matrix6)


matrix4:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

matrix5:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

matrix eye:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [54]:
# defining an array with values 0 to 9
arr4 = np.arange(0,10) 
print('arr4 is',arr4)

# reshaping the array arr4 to a 2 x 5 matrix
arr4_reshaped = arr4.reshape((2,5))
print('\nReshaped to Matrix 2, 5)\n',arr4_reshaped)
print('reshaped array to 5x2 matrix\n', arr4.reshape(5,2))

arr5 = np.arange(0,9)
arr5_reshaped = arr5.reshape((3,3))
print('\narr5\n',arr5)
print('Reshaped arr5 to 3x3 matrix\n',arr5_reshaped)

arr4 is [0 1 2 3 4 5 6 7 8 9]

Reshaped to Matrix 2, 5)
 [[0 1 2 3 4]
 [5 6 7 8 9]]
reshaped array to 5x2 matrix
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

arr5
 [0 1 2 3 4 5 6 7 8]
Reshaped arr5 to 3x3 matrix
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**Trigonometric functions**

In [60]:
print('Sine Function:',np.sin(4))
print('Cosine Function:',np.cos(4))
print('Tan Function',np.tan(4))


Sine Function: -0.7568024953079283
Cosine Function: -0.6536436208636119
Tan Function 1.1578212823495775


In [67]:
print('exponant of 0 is', np.exp(0))
print('log of 1 is', np.log(1))



exponant of 0 is 1.0
log of 1 is 0.0


In [77]:
arr5 = np.array([2,4,6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [78]:
# by default NumPy takes the base of log as e
np.log(2)

0.6931471805599453

In [79]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [80]:
np.log10(arr5)

array([0.30103   , 0.60205999, 0.77815125])

**Arithmatic Operations in Arrays**

In [81]:
# arithmetic on lists

l1 = [1,2,3]
l2 = [4,5,6]
print(l1+l2)
# this does not behave as you would expect!
# Concatenates two lists instead of adding them together.


[1, 2, 3, 4, 5, 6]


In [85]:
# we can +-*/ arrays together

# defining two arrays
arr7 = np.arange(1,6)
print('arr7:', arr7)

arr8 = np.arange(3,8)
print('arr8:', arr8)

# adding them together
print('arr7 + arr8:', arr7 + arr8)

# subtracting them together
print('arr7 - arr8:', arr7 - arr8)

# multiplying them together 
print('arr7 * arr8:', arr7 * arr8)

# dividing them together
print('arr7 / arr8:', arr7 / arr8)

#Inverse
print('Inverse of arr7:', 1/(arr7))

#powers
print('arr7 ** arr8:', arr7 ** arr8)


arr7: [1 2 3 4 5]
arr8: [3 4 5 6 7]
arr7 + arr8: [ 4  6  8 10 12]
arr7 - arr8: [-2 -2 -2 -2 -2]
arr7 * arr8: [ 3  8 15 24 35]
arr7 / arr8: [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse of arr7: [1.         0.5        0.33333333 0.25       0.2       ]
arr7 ** arr8: [    1    16   243  4096 78125]


**Operations on Matrix**

In [89]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8 = np.eye(3)
print(matrix8)

print('Addition: \n', matrix7+matrix8)
print('Subtraction: \n ', matrix7-matrix8)
print('Multiplication: \n', matrix7*matrix8)
print('Division: \n', matrix7/matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


/var/folders/hn/gtr1m4r92597m52h_j8yq2c00000gn/T/ipykernel_33086/1269734437.py:10: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix7/matrix8)


**Linear Algebra Matrix Multiplication**

In [101]:
matrix9 = np.arange(1,10).reshape(3,3)
print('First Matrix: \n',matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print('Second Matrix: \n',matrix10)
print('')
# taking linear algebra matrix multiplication (some may have heard this called the dot product)
print('Multiplication: \n', matrix9 @ matrix10)

print('\n\nTranspose: \n', matrix7, '\nequivalent to \n', matrix7.T)
np.transpose(matrix7)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


Transpose: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
equivalent to 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [104]:
print('Min of matrix7 is ', np.min(matrix7))
print('Max of matrix7 is ', np.max(matrix7))

Min of matrix7 is  1
Max of matrix7 is  9


**Random functions in numpy**

In [142]:
int_mat = np.random.randint(0, 100, size=(3, 3))

rad_mat2 = np.random.randn(3, 3)

print('Mean of rad_mat2: {}'.format(np.mean(rad_mat2)),round(np.mean(rad_mat2),4))
print('Median of rad_mat2: {}'.format(np.median(rad_mat2)), round(np.median(rad_mat2),4))

print('Standard deviation of rad_mat2: {}'.format(np.std(rad_mat2)),round(np.std(rad_mat2),4))

Mean of rad_mat2: 0.36764589715429247 0.3676
Median of rad_mat2: 0.2261098076045134 0.2261
Standard deviation of rad_mat2: 1.142628651676325 1.1426


In [126]:
# let's generate an array with 10 random values
rand_arr = np.random.randn(10)
print(rand_arr)

# accessing the 6 th entry of rand_arr
print('6 th entry of rand_arr', rand_arr[6])

# we can access multiple entries at once using
print('\naccess multiple entries at once using rand_arr[4:9]\n', rand_arr[4:9])

[ 0.1869693  -0.14165787  0.18763621  0.77276326 -0.38927029  0.08944631
 -1.34199507  2.2131202  -0.62200716 -0.31182739]
6 th entry of rand_arr -1.3419950683454065

access multiple entries at once using rand_arr[4:9]
 [-0.38927029  0.08944631 -1.34199507  2.2131202  -0.62200716]


In [127]:
# we can also access multiple non-consecutive entries using np.arange
print('Index of values to access: ',np.arange(3,10,3))
print(rand_arr[np.arange(3,10,3)])

Index of values to access:  [3 6 9]
[ 0.77276326 -1.34199507 -0.31182739]


In [130]:
print('rand_arr values >0 are', rand_arr>0)

# accessing all the values of rand_arr which are greater than 0
print('Values greater than 0: ',rand_arr[rand_arr>0])

# accessing all the values of rand_arr which are less than 0
print('Values less than 0: ',rand_arr[rand_arr<0])

rand_arr values >0 are [ True False  True  True False  True False  True False False]
Values greater than 0:  [0.1869693  0.18763621 0.77276326 0.08944631 2.2131202 ]
Values less than 0:  [-0.14165787 -0.38927029 -1.34199507 -0.62200716 -0.31182739]


In [141]:
print([i for i, x in enumerate(rand_arr) if x > 0])
print(rand_arr[[i for i, x in enumerate(rand_arr) if x > 0]])

[0, 2, 3, 5, 7]
[0.1869693  0.18763621 0.77276326 0.08944631 2.2131202 ]


**Accessing Matrix Data**

In [145]:
# let's generate an array with 10 random values
rand_mat = np.random.randn(5,5)
print(rand_mat)

# acessing third element of the second row
print(rand_mat[1][2])

#or 

print(rand_mat[1,2])

# accessing first two rows with second and third column 
print(rand_mat[0:2,1:3])

[[-1.31213026  0.76623925 -1.19627106  0.64600053 -0.62017967]
 [-1.12080531 -0.58909086  0.35358714 -0.37653943  1.0801799 ]
 [-1.89493834  0.12401185  0.68964589 -1.64221988 -1.44005918]
 [-0.26805288 -0.09981414 -0.49773025  0.63723555  0.40334015]
 [-1.30875886  0.57232547  1.0902531   0.02800017  0.16321003]]
0.35358713694468247
0.35358713694468247
[[ 0.76623925 -1.19627106]
 [-0.58909086  0.35358714]]


In [153]:
# accessing all the values of rand_mat which are greater than 0
print('Values greater than 0: \n ',rand_mat[rand_mat>0])

# accessing all the values of rand_mat which are less than 0
print('Values less than 0: \n',rand_mat[rand_mat<0])

Values greater than 0: 
  [0.76623925 0.64600053 0.35358714 1.0801799  0.12401185 0.68964589
 0.63723555 0.40334015 0.57232547 1.0902531  0.02800017 0.16321003]
Values less than 0: 
 [-1.31213026 -1.19627106 -0.62017967 -1.12080531 -0.58909086 -0.37653943
 -1.89493834 -1.64221988 -1.44005918 -0.26805288 -0.09981414 -0.49773025
 -1.30875886]


**Modifying entries of an array**

In [147]:
# let's change some values in an array!
# changing the values of index value 3 and index value 4 to 5
rand_arr[3:5] = 5
print(rand_arr)

[ 0.1869693  -0.14165787  0.18763621  5.          5.          0.08944631
 -1.34199507  2.2131202  -0.62200716 -0.31182739]


In [148]:
# changing the values of index value 0 and index value 1 to 2 and 3 respectively
rand_arr[0:2] = [2,3]
print(rand_arr)

[ 2.          3.          0.18763621  5.          5.          0.08944631
 -1.34199507  2.2131202  -0.62200716 -0.31182739]


In [149]:
# modify entries using logical references
rand_arr[rand_arr>0] = 65
rand_arr

array([65.        , 65.        , 65.        , 65.        , 65.        ,
       65.        , -1.34199507, 65.        , -0.62200716, -0.31182739])

***Modify matix entities***

In [158]:
# Generating random values in an array
rand_mat3 = np.random.randint(1,5,10)
print(rand_mat3)

# Generating random values in a matrix
rand_mat3 = np.random.randint(1,10,[5,5])
print(rand_mat3)

[4 1 4 2 4 3 2 1 2 2]
[[2 5 7 7 3]
 [2 9 9 2 8]
 [3 9 3 4 9]
 [9 5 5 9 7]
 [1 5 5 9 6]]


In [159]:
# changing the values of the 4th and 5th element of the second and third rows of the matrix to 0
print('Matrix before modification: \n',rand_mat3)
rand_mat3[1:3,3:5] = 0
print('Matrix after modification: \n',rand_mat3)

Matrix before modification: 
 [[2 5 7 7 3]
 [2 9 9 2 8]
 [3 9 3 4 9]
 [9 5 5 9 7]
 [1 5 5 9 6]]
Matrix after modification: 
 [[2 5 7 7 3]
 [2 9 9 0 0]
 [3 9 3 0 0]
 [9 5 5 9 7]
 [1 5 5 9 6]]


In [161]:
# extracting the first 2 rows and first 3 columns from the matrix
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
print(rand_mat)

[[-1.31213026  0.76623925 -1.19627106]
 [-1.12080531 -0.58909086  0.35358714]]
[[-1.31213026  0.76623925 -1.19627106  0.64600053 -0.62017967]
 [-1.12080531 -0.58909086  0.35358714 -0.37653943  1.0801799 ]
 [-1.89493834  0.12401185  0.68964589 -1.64221988 -1.44005918]
 [-0.26805288 -0.09981414 -0.49773025  0.63723555  0.40334015]
 [-1.30875886  0.57232547  1.0902531   0.02800017  0.16321003]]


In [162]:
# changing all the values of the extracted matrix to 3
sub_mat[:] = 3
print(sub_mat)
print(rand_mat)

[[3. 3. 3.]
 [3. 3. 3.]]
[[ 3.          3.          3.          0.64600053 -0.62017967]
 [ 3.          3.          3.         -0.37653943  1.0801799 ]
 [-1.89493834  0.12401185  0.68964589 -1.64221988 -1.44005918]
 [-0.26805288 -0.09981414 -0.49773025  0.63723555  0.40334015]
 [-1.30875886  0.57232547  1.0902531   0.02800017  0.16321003]]


In [165]:
# to prevent this behavior we need to use the .copy() method when we assign sub_mat
# this behavior is the source of MANY errors for early python users!!!

rand_mat = np.random.randn(5,5)
print('Ran mat init\n',rand_mat)
sub_mat = rand_mat[0:2,0:3].copy()
print('\nGent sub mat\n',sub_mat)
sub_mat[:] = 3
print('\nManipulate sub mat\n', sub_mat)
print('\nAfrer manipulation\n', rand_mat)

Ran mat init
 [[-1.49531282  0.03415959 -0.21380921  0.32174969  0.59968743]
 [-0.18741669 -0.70185737 -1.09807461 -1.06753011 -1.43458375]
 [ 2.04222359  1.18777385 -0.23271279  0.56554057 -0.64556264]
 [ 0.14919126 -1.98126024  0.0353187   0.89143227 -0.69400569]
 [-0.65447314 -0.35131833  1.11218198  0.00649183 -1.25222383]]

Gent sub mat
 [[-1.49531282  0.03415959 -0.21380921]
 [-0.18741669 -0.70185737 -1.09807461]]

Manipulate sub mat
 [[3. 3. 3.]
 [3. 3. 3.]]

Afrer manipulation
 [[-1.49531282  0.03415959 -0.21380921  0.32174969  0.59968743]
 [-0.18741669 -0.70185737 -1.09807461 -1.06753011 -1.43458375]
 [ 2.04222359  1.18777385 -0.23271279  0.56554057 -0.64556264]
 [ 0.14919126 -1.98126024  0.0353187   0.89143227 -0.69400569]
 [-0.65447314 -0.35131833  1.11218198  0.00649183 -1.25222383]]


In [166]:
np.save('matdata.txt',rand_mat)

OSError: [Errno 30] Read-only file system: 'matdata.txt.npy'

In [167]:
my_numpy_array = np.array([1, 2, 'hello', 3.14])

In [168]:
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


In [169]:
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [170]:
vec = np.arange(10, 20, 3)
print(vec)

[10 13 16 19]


In [171]:
vec = np.linspace(10,20,3)
print(vec)

[10. 15. 20.]


In [172]:
vec = np.zeros([2,3])
print(vec)

[[0. 0. 0.]
 [0. 0. 0.]]


In [173]:
vec1 = np.arange(0, 12)
vec2 = vec1.reshape(4, 3)
print(vec2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [179]:
mat1 = np.arange(10).reshape(2, 5)
mat2 = np.arange(9).reshape(3,3)

mat2 * mat1

ValueError: operands could not be broadcast together with shapes (3,3) (2,5) 

In [180]:
vec1 = [10,15,20]
vec2 = [15,25,35]
print(vec1+vec2)

[10, 15, 20, 15, 25, 35]


In [183]:
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1, vec2)
print(vec1 + vec2)

[20. 30. 40. 50.] [100. 110. 120.]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [184]:
vec = np.arange(2,5,1)
print(1/vec)
print(vec**2)

[0.5        0.33333333 0.25      ]
[ 4  9 16]


In [185]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1/mat2)

[[ 1. inf]
 [inf  4.]]


/var/folders/hn/gtr1m4r92597m52h_j8yq2c00000gn/T/ipykernel_33086/3306162440.py:3: RuntimeWarning: divide by zero encountered in divide
  print(mat1/mat2)


In [186]:
mat1 = np.arange(-9,0,1).reshape(3,3)
print(np.min(mat1))
print(np.max(mat1))

-9
-1


In [187]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [188]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [189]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [190]:
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [193]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array1

print(array1)
print(array2)

array2[0,1] = 100

print(array1)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1 100   3]
 [  4   5   6]
 [  7   8   9]]
[[  1 100   3]
 [  4   5   6]
 [  7   8   9]]


In [206]:
import pandas as pd
pd.DataFrame() #- works with pandas
# pd.Dataframe() - Error
# pd.dataframe()
#pd.DATAFRAME()


Empty DataFrame
Columns: []
Index: []

In [209]:
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)
temp_data[:2]

day1    31
day2    28
dtype: int64

In [210]:
temp_data['day3']

30

In [212]:
temp_data[2:]

day3    30
day4    32
dtype: int64

In [214]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data[:2]

day  calories  duration_min
0  day1       450            30
1  day2       300            25

In [216]:
calorie_data['calories']

0    450
1    300
2    345
3    520
4    600
Name: calories, dtype: int64

In [217]:
calorie_data[::2]

day  calories  duration_min
0  day1       450            30
2  day3       345            29
4  day5       600            48

In [222]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data.loc[0]

day             day1
calories         450
duration_min      30
Name: 0, dtype: object

In [223]:

calorie_data.iloc[[1,2],[1]]

 

calories
1       300
2       345

In [224]:
 calorie_data.loc[[1,2],['calories']]

calories
1       300
2       345

In [225]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data

day  calories  duration_min
0  day1       450            30
1  day2       300            25
2  day3       345            29
3  day4       520            39
4  day5       600            48

In [226]:
calorie_data.loc[calorie_data['calories']>500]

day  calories  duration_min
3  day4       520            39
4  day5       600            48

In [228]:
calorie_data.drop('duration_min',axis=1)

day  calories
0  day1       450
1  day2       300
2  day3       345
3  day4       520
4  day5       600

In [231]:
calorie_data

day  calories  duration_min
0  day1       450            30
1  day2       300            25
2  day3       345            29
3  day4       520            39
4  day5       600            48

In [242]:
calorie_data['calories'].unique()

array([450, 300, 345, 520, 600])

In [245]:
calorie_data[0,2] = 600

In [249]:
calorie_data.loc[0,['calorie']] = 600

In [250]:
calorie_data

day  calories  duration_min  (0, 2)  calorie
0  day1       450            30     600    600.0
1  day2       300            25     600      NaN
2  day3       345            29     600      NaN
3  day4       520            39     600      NaN
4  day5       600            48     600      NaN

In [293]:
calorie_data['calories'].unique()

array([450, 300, 345, 520, 600])

In [270]:
import datetime as dt
data = dt.date(2022, 12, 29)
print(data)

2022-12-29


In [275]:
dat = '2023-12-12'
dat['date'].dt.month

TypeError: string indices must be integers, not 'str'

In [276]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [281]:
demo_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

demo_array

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [285]:


# Replace the first 7 elements with the value 5
demo_array[:7] = [5] * 7

print(demo_array)

[5, 8, 9, 10]


In [288]:
demo_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


TypeError: can only assign an iterable

In [289]:
import numpy as np
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [290]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5

In [301]:
data_customer = pd.DataFrame({'customer': [101, 102, 103, 104]
                           ,'catogery': ['cat1', 'cat2', 'cat3', 'cat4']
                           ,'important': ['yes', 'no', 'yes', 'no']
                           , 'sales':[123,52,214,663]
                           })
data_customer 

customer catogery important  sales
0       101     cat1       yes    123
1       102     cat2        no     52
2       103     cat3       yes    214
3       104     cat4        no    663

In [302]:
data_customer['customer'].value_counts()

customer
101    1
102    1
103    1
104    1
Name: count, dtype: int64

In [303]:
data_customer.sort_values(by='sales',ascending=False)

customer catogery important  sales
3       104     cat4        no    663
2       103     cat3       yes    214
0       101     cat1       yes    123
1       102     cat2        no     52

In [308]:
#data_customer.loc[1:3, ['customer', 'sales']]
data_customer.loc[[1,2], ['customer', 'sales']]

customer  sales
1       102     52
2       103    214

In [310]:
data_cust = pd.DataFrame({'customer': [101, 102, 103, 104,101,103]
                           ,'catogery': ['cat1', 'cat2', 'cat3', 'cat4','cat2','cat1']
                           ,'important': ['yes', 'no', 'yes', 'no', 'yes', 'yes']
                           , 'sales':[123,52,214,663,204,453]
                           })
data_cust

customer catogery important  sales
0       101     cat1       yes    123
1       102     cat2        no     52
2       103     cat3       yes    214
3       104     cat4        no    663
4       101     cat2       yes    204
5       103     cat1       yes    453

In [312]:
data_cust.groupby(['customer'])['sales'].mean()

customer
101    163.5
102     52.0
103    333.5
104    663.0
Name: sales, dtype: float64

In [313]:
np.array([1,10,21,35,72]) 

array([ 1, 10, 21, 35, 72])

In [314]:
np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [315]:
np.array([[9, 8, 7, 6, 5, 4, 3, 2, 1]])

array([[9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [316]:
np.arange(start=1, stop=10, step=1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [318]:
array_1 = np.linspace(0,20,6)
array_1

array([ 0.,  4.,  8., 12., 16., 20.])

In [319]:
array_2 = np.arange(0,20,6)
array_2

array([ 0,  6, 12, 18])

In [322]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256], 
                [ 49, 64, 81, 289, 324, 361]])

mat.mean()

131.66666666666666

In [323]:
a = np.arange(0,20)
a[2:7]

array([2, 3, 4, 5, 6])

In [324]:
np.cos([0, 1, 2, 3, 4]) 

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [326]:
list_1 = [1,2,3] 
list_2 = [4,5,6]
new_list = list_1 + list_2

array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2

In [327]:
print(new_list, "\n\n")
print(new_array)

[1, 2, 3, 4, 5, 6] 


[5 7 9]


In [328]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])


In [329]:
mat[1] = 5


In [330]:
mat[2] = 5

In [331]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])



21


In [332]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [333]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])

n1@n2

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [335]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat

array([[1, 2, 1],
       [4, 5, 9],
       [1, 8, 9]])

In [336]:
mat[1] = 5

mat

array([[1, 2, 1],
       [5, 5, 5],
       [1, 8, 9]])

In [339]:
bk = pd.read_csv('~/Downloads/books.csv')

In [340]:
bk

title  \
0                           The Hunchback of Notre-Dame   
1     La Cucina Di Lidia: Recipes and Memories from ...   
2                                     Breach of Promise   
3                     Brief Interviews with Hideous Men   
4     The Killing Dance (Anita Blake  Vampire Hunter...   
...                                                 ...   
4995                                 The Complete Works   
4996                               Shipwreck (Island I)   
4997           Every Night Italian: Every Night Italian   
4998                                     Go Down  Moses   
4999  The Avignon Quintet: Monsieur  Livia  Constanc...   

                           author  average_rating         isbn13  \
0                     Victor Hugo            4.00  9780345472427   
1     Lidia Matticchio Bastianich            4.14  9780767914222   
2                James Scott Bell            4.00  9780310243878   
3            David Foster Wallace            3.86  9780349111889   
4             Laurell K. Hamilton            4.13  9780425209066   
...                           ...             ...            ...   
4995          Michel de Montaigne            4.44  9781400040216   
4996                Gordon Korman            3.80  9780439023313   
4997               Giuliano Hazan            3.79  9780684800288   
4998             William Faulkner            3.93  9780679732174   
4999             Lawrence Durrell            4.07  9780571225552   

     language_code  num_pages  ratings_count  text_reviews_count  \
0            en-US      534.0            140                  22   
1            en-GB      288.0             48                   3   
2              eng      345.0            368                  36   
3              eng      273.0          18335                1155   
4            en-US      368.0          59524                 946   
...            ...        ...            ...                 ...   
4995           eng     1392.0            166                  13   
4996           eng        NaN            103                  14   
4997           eng      256.0             70                   2   
4998           eng      365.0           8289                 370   
4999         en-US     1376.0            287                  23   

                   publisher  year  
0             Modern Library  2004  
1            Clarkson Potter  2003  
2                  Zondervan  2004  
3                     Abacus  2000  
4          Berkley Hardcover  2006  
...                      ...   ...  
4995      Everyman's Library  2003  
4996  Scholastic Audio Books  2007  
4997                Scribner  2000  
4998                 Vintage  1991  
4999           Faber & Faber  2004  

[5000 rows x 10 columns]

In [342]:
bk.describe()

average_rating        isbn13    num_pages  ratings_count  \
count     5000.000000  5.000000e+03  4967.000000   5.000000e+03   
mean         3.931932  9.752758e+12   341.094021   2.017549e+04   
std          0.348741  5.129254e+11   230.986115   1.175026e+05   
min          0.000000  8.987060e+09     1.000000   0.000000e+00   
25%          3.770000  9.780345e+12   200.000000   1.050000e+02   
50%          3.960000  9.780571e+12   304.000000   7.915000e+02   
75%          4.140000  9.780871e+12   416.500000   5.348750e+03   
max          5.000000  9.789879e+12  3342.000000   2.457092e+06   

       text_reviews_count         year  
count         5000.000000  5000.000000  
mean           592.688600  2000.131800  
std           2539.539004     8.069043  
min              0.000000  1913.000000  
25%              9.000000  1998.000000  
50%             49.000000  2003.000000  
75%            249.000000  2005.000000  
max          55843.000000  2019.000000

In [347]:


# Assuming df is your DataFrame
object_columns = bk.select_dtypes(include='object').columns

# Count the number of object columns
num_object_columns = len(object_columns)

print(f"Number of columns with object datatype: {num_object_columns}")

Number of columns with object datatype: 4


In [354]:
books_greater_than_4 = bk[bk['average_rating'] > 4]

# Count the number of books with an average rating greater than 4
num_books_greater_than_4 = len(books_greater_than_4)

print(f"Number of books with an average rating greater than 4: {num_books_greater_than_4}")

Number of books with an average rating greater than 4: 2115


In [356]:
df = bk

In [360]:
df[(df['average_rating']>4.5) & (df['ratings_count']<10)].count

<bound method DataFrame.count of                                                   title  \
63                                             鋼之鍊金術師 9   
178                                            鋼之鍊金術師 6   
224                             Stargirl LitPlans on CD   
454   Literature Circle Guide: Bridge to Terabithia:...   
584                       Falling Angels (Luc Actar #1)   
681        Fanning the Flame: Bible  Cross  and Mission   
696                  Tyrannosaurus Wrecks (Stanley  #1)   
741   The John Deere Two-Cylinder Tractor Encycloped...   
757   The American Campaign: U.S. Presidential Campa...   
1837  The Goon Show  Volume 4: My Knees Have Fallen ...   
1856                                          鋼之鍊金術師 10   
1960  Wissenschaft der Logik: Die Lehre Vom Begriff ...   
2244  Getting a Grip on the Basics: Building a Firm ...   
2496                               Come Away My Beloved   
3178  Organizational Architecture: Designs for Chang...   
3438         Bill Gates

In [361]:
df.groupby(['language_code'])['average_rating'].mean()

language_code
en-GB    3.922523
en-US    3.914800
eng      3.931143
ger      3.979773
grc      2.366667
jpn      4.252381
lat      4.170000
mul      4.116000
spa      3.927938
Name: average_rating, dtype: float64

In [363]:
df.iloc[0:5,0:4]

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13  
0                  Victor Hugo            4.00  9780345472427  
1  Lidia Matticchio Bastianich            4.14  9780767914222  
2             James Scott Bell            4.00  9780310243878  
3         David Foster Wallace            3.86  9780349111889  
4          Laurell K. Hamilton            4.13  9780425209066

In [364]:
df.loc[[1, 5],['language_code', 'num_pages', 'ratings_count']]

language_code  num_pages  ratings_count
1         en-GB      288.0             48
5           eng      446.0          16301

In [370]:
df['num_pages'].mean()

341.0940205355345

In [378]:
df.describe

<bound method NDFrame.describe of                                                   title  \
0                           The Hunchback of Notre-Dame   
1     La Cucina Di Lidia: Recipes and Memories from ...   
2                                     Breach of Promise   
3                     Brief Interviews with Hideous Men   
4     The Killing Dance (Anita Blake  Vampire Hunter...   
...                                                 ...   
4995                                 The Complete Works   
4996                               Shipwreck (Island I)   
4997           Every Night Italian: Every Night Italian   
4998                                     Go Down  Moses   
4999  The Avignon Quintet: Monsieur  Livia  Constanc...   

                           author  average_rating         isbn13  \
0                     Victor Hugo            4.00  9780345472427   
1     Lidia Matticchio Bastianich            4.14  9780767914222   
2                James Scott Bell            4.00  97

In [426]:
(df[(df['year']>2010) & 
    (df['num_pages']>500)]).shape[0]

5

In [425]:
c = df[df['num_pages']>500 ]
c.groupby('year').count()

title  author  average_rating  isbn13  language_code  num_pages  \
year                                                                    
1925      1       1               1       1              1          1   
1954      1       1               1       1              1          1   
1957      1       1               1       1              1          1   
1965      1       1               1       1              1          1   
1968      2       2               2       2              2          2   
1971      1       1               1       1              1          1   
1972      1       1               1       1              1          1   
1973      1       1               1       1              1          1   
1975      2       2               2       2              2          2   
1976      3       3               3       3              3          3   
1977      6       6               6       6              6          6   
1978      1       1               1       1              1          1   
1979      1       1               1       1              1          1   
1980      3       3               3       3              3          3   
1981      1       1               1       1              1          1   
1982      4       4               4       4              4          4   
1983      4       4               4       4              3          4   
1984     10      10              10      10             10         10   
1985      8       8               8       8              8          8   
1986      5       5               5       5              4          5   
1987      6       6               6       6              6          6   
1988      7       7               7       7              7          7   
1989      3       3               3       3              3          3   
1990      8       8               8       8              8          8   
1991     13      13              13      13             13         13   
1992     17      17              17      17             17         17   
1993     14      14              14      14             14         14   
1994     18      18              18      18             18         18   
1995     19      19              19      19             19         19   
1996     23      23              23      23             23         23   
1997     21      21              21      21             21         21   
1998     35      35              35      35             34         35   
1999     28      28              28      28             28         28   
2000     40      40              40      40             40         40   
2001     52      52              52      52             49         52   
2002     62      62              62      62             58         62   
2003     59      59              59      59             57         59   
2004     75      75              75      75             73         75   
2005     84      84              84      84             82         84   
2006     85      85              85      85             83         85   
2007     33      33              33      33             33         33   
2008      2       2               2       2              2          2   
2009      5       5               5       5              5          5   
2010      1       1               1       1              1          1   
2011      3       3               3       3              3          3   
2017      2       2               2       2              2          2   

      ratings_count  text_reviews_count  publisher  
year                                                
1925              1                   1          1  
1954              1                   1          1  
1957              1                   1          1  
1965              1                   1          1  
1968              2                   2          2  
1971              1                   1          1  
1972              1                   1          1  
1973              1     

In [414]:
len(df[df['publisher'] == 'DAW']['average_rating']>4)

17

In [416]:
len(df[df['author'] == "Agatha Christie"])

21

In [424]:
c = df[df['year']>2000 ]
c.groupby('language_code').count()

title  author  average_rating  isbn13  num_pages  \
language_code                                                     
en-GB             70      70              70      70         69   
en-US            451     451             451     451        446   
eng             2476    2476            2476    2476       2456   
ger               28      28              28      28         28   
jpn               13      13              13      13         13   
lat                1       1               1       1          1   
mul                2       2               2       2          2   
spa               84      84              84      84         83   

               ratings_count  text_reviews_count  publisher  year  
language_code                                                      
en-GB                     70                  70         70    70  
en-US                    451                 451        451   451  
eng                     2476                2476       2476  2476  
ger                       28                  28         28    28  
jpn                       13                  13         13    13  
lat                        1                   1          1     1  
mul                        2                   2          2     2  
spa                       84                  84         84    84